genetic_algorithm:
    num_generations: 200
    population_size: 100
    num_features: 2
    num_bits_per_feature: 22
    min_value: -100
    max_value: 100
    crossover_rate: 0.65
    mutation_rate: 0.008
    round_decimals: 6
    plot_individuals: true