genetic_algorithm:
    num_generations: 200
    population_size: 200
    num_features: 2
    num_bits_per_feature: 22
    min_value: -100
    max_value: 100
    population_generation_seed: 42
    crossover_rate: 0.65
    mutation_rate: 0.008